# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gayilTSWMUXTPxxvreLHxqiz7TUfYPgA
"""

import streamlit as st
import pandas as pd
from sklearn.linear_model import LinearRegression

# Sample data
data = {
    "fuel": [10.5, 9.8, 13.7, 15.0, 11.4, 10.6, 10.8, 15.2, 15.4],
    "co2": [216, 205, 265, 301, 230, 219, 223, 306, 306]
}

df = pd.DataFrame(data)

# Train model
model = LinearRegression()
model.fit(df[["fuel"]], df["co2"])

# Page settings
st.set_page_config(
    page_title="CO₂ Emissions Predictor",
    page_icon="🚗",
    layout="centered"
)

st.title("🚗 Vehicle CO₂ Emissions Predictor")

st.markdown("""
Predict vehicle CO₂ emissions using a Linear Regression model trained on
fuel consumption data.
""")

st.divider()

fuel = st.slider(
    "⛽ Fuel Consumption (L/100km)",
    min_value=0.0,
    max_value=20.0,
    value=10.0
)

if st.button("Predict Emissions"):
    prediction = model.predict([[fuel]])

    st.metric(
        label="🌍 Predicted CO₂ Emissions",
        value=f"{prediction[0]:.2f} g/km"
    )

st.divider()

st.caption(
    "Built with Python, Scikit-Learn, and Streamlit"
)

st.sidebar.title("About Project")

st.sidebar.info("""
Machine Learning Model:
Linear Regression

Input:
Fuel Consumption

Output:
CO₂ Emissions

Developed by Amna
""")