# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gayilTSWMUXTPxxvreLHxqiz7TUfYPgA
"""

import streamlit as st
import pandas as pd
from sklearn.linear_model import LinearRegression

data = {
    "fuel": [10.5, 9.8, 13.7, 15.0, 11.4],
    "co2": [216, 205, 265, 301, 230]
}

df = pd.DataFrame(data)

model = LinearRegression()
model.fit(df[["fuel"]], df["co2"])

fuel = st.number_input("Fuel Consumption")

if st.button("Predict"):
    pred = model.predict([[fuel]])
    st.write(f"Predicted CO₂ Emissions: {pred[0]:.2f}")