# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gayilTSWMUXTPxxvreLHxqiz7TUfYPgA
"""

import streamlit as st
import os

st.write(os.listdir("."))

import streamlit as st
import joblib

# Load trained model
model = joblib.load("model.pkl")

st.title("CO₂ Emissions Predictor")

fuel = st.number_input(
    "Enter Fuel Consumption",
    min_value=0.0,
    value=10.0
)

if st.button("Predict"):
    prediction = model.predict([[fuel]])
    st.success(f"Predicted CO₂ Emissions: {prediction[0]:.2f}")