# -*- coding: utf-8 -*-
"""model.pkl

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JI-_KZvp1wEGZQ1RrLZAQQnA-Jrro5BV
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

import pandas as pd
df= pd.read_excel('/content/drive/MyDrive/FuelConsumption.xlsx')
df

x=df[['FUEL CONSUMPTION']]
y=df['COEMISSIONS']
plt.xlabel('FUEL CONSUMPTION',color="red")
plt.ylabel('COEMISSIONS',color="red")
plt.scatter(df['FUEL CONSUMPTION'], df['COEMISSIONS'])

lr=linear_model.LinearRegression()
lr.fit(df[['FUEL_CONSUMPTION']],df.COEMISSIONS)

lr.predict([[16]])

lr.score(df[['FUEL_CONSUMPTION']],df.COEMISSIONS)

lr.coef_

lr.intercept_

predicted=18.00639233*16+25.390245990525642
print(predicted)

plt.xlabel('FUEL CONSUMPTION', color="red")
plt.ylabel('COEMISSIONS', color="red")
plt.scatter(df['FUEL CONSUMPTION'], df['COEMISSIONS'])

df_plot = df.sort_values(by='FUEL CONSUMPTION').copy()
predictions_for_plot = lr.predict(df_plot[['FUEL CONSUMPTION']])
plt.plot(df_plot['FUEL CONSUMPTION'], predictions_for_plot, color='blue')

# Display the plot
plt.show()

from sklearn.linear_model import LinearRegression
import joblib

X = df[['FUEL_CONSUMPTION']]
y = df['COEMISSIONS']

model = LinearRegression()
model.fit(X, y)

joblib.dump(model, "model.pkl")